### ISSUE TITLE
[Bug] Screen flickers

### ISSUE THREAD

**Issue by tmschorr** [NightmareXIV/Weatherman#21]
For example, when I do the quest "Tines of the Trident" and I defeat the corresponding enemies, the screen flickers briefly before new enemies are spawned because it displays the real time of day before it resumes the time of day I selected.

**Comment by Limiana** [comment]
Hello, try turning off "disable plugin in cutscenes" option

**Comment by tmschorr** [comment]
Seems to work - thank you
