### ISSUE TITLE
Plugin seems to cause a 1m30 long freeze on bootup

### ISSUE THREAD

**Issue by Tenrys** [NightmareXIV/Weatherman#23]
I feel like this has to be some obscure conflict between this plugin and my other 84, along with GShade, but from my testing taking half of them away after I reboot the game each time, Weatherman was the plugin causing it.

Logs didn't seem to look abnormal, is there something I can do to help debug this further? For the time I'm just going to only load the plugin when I need it.

**Comment by Limiana** [comment]
I can make a version that includes extensive logging during boot process. I will let you know when it's ready.

**Comment by Limiana** [comment]
@Tenrys 
[latest.zip](https://github.com/NightmareXIV/Weatherman/files/10732874/latest.zip)
I have made a debug build for you, so please do the following:
1) Close the game completely
2) go to `%appdata%\XIVLauncher\installedPlugins\Weatherman\2.4.0.7` and delete contents of this folder
3) replace contents of mentioned above folder with contents of this archive
4) Load the game again
5) Wait until all plugins are loaded, then attach your `%appdata%\XIVLauncher\dalamud.log` file to the message
