### ISSUE TITLE
[Feature Request] Sync with real time

### ISSUE THREAD

**Issue by Lovasz-Akos** [NightmareXIV/Weatherman#36]
May be odd but I'd love a checkbox that syncs the in game time to my local system's time so I could have real-time progress of the day instead of the 72 minute cycle

**Comment by Limiana** [comment]
Hello!
![image](https://github.com/user-attachments/assets/80da94e3-138a-4a09-acf3-12fbbc1f7624)
Already possible, see last option

**Comment by Lovasz-Akos** [comment]
oh damn, guess I wasn't thorough enough when looking around, thanks!
